name: Trigger auto deployment for jobradar-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jobradar-backend-AutoDeployTrigger-eb1d9efc-5b13-437a-828f-fa83e2963932.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.JOBRADARBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JOBRADARBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JOBRADARBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: jobradarregistry.azurecr.io
          registryUsername: ${{ secrets.JOBRADARBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JOBRADARBACKEND_REGISTRY_PASSWORD }}
          containerAppName: jobradar-backend
          resourceGroup: jobradar-rg
          imageToBuild: jobradarregistry.azurecr.io/jobradar-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


